import { c as create_ssr_component, e as escape, b as subscribe, v as validate_component } from "../../chunks/ssr.js";
import { p as page } from "../../chunks/stores.js";
const css$2 = {
  code: ".courier-font.svelte-7rkn24{font-family:'Courier New', Courier, monospace}",
  map: `{"version":3,"file":"header.svelte","sources":["header.svelte"],"sourcesContent":["<!-- usr/local/var/www/mjjun/src/lib/components/header.svelte -->\\n\\n<script>\\n\\timport { page } from '$app/stores';\\n\\timport { onMount } from 'svelte';\\n<\/script>\\n\\n<header class=\\"courier-font w-full bg-white shadow-sm\\">\\n\\t<div class=\\"container mx-auto px-4 sm:px-6 lg:px-8\\">\\n\\t\\t<div class=\\"flex items-center justify-between py-4\\">\\n\\t\\t\\t<div class=\\"flex items-center\\">\\n\\t\\t\\t\\t<a href=\\"/\\" class=\\"flex items-center text-xl font-bold text-gray-800\\">\\n\\t\\t\\t\\t\\t<img src=\\"/logo_mj.png\\" alt=\\"Logo\\" class=\\"h-8\\" />\\n\\t\\t\\t\\t</a>\\n\\n\\t\\t\\t\\t<nav class=\\"ml-6\\">\\n\\t\\t\\t\\t\\t<a href=\\"/work\\" class=\\"text-gray-800 hover:text-gray-600 transition-colors duration-200\\">\\n\\t\\t\\t\\t\\t\\tmy works\\n\\t\\t\\t\\t\\t</a>\\n\\t\\t\\t\\t</nav>\\n\\t\\t\\t</div>\\n\\t\\t</div>\\n\\t</div>\\n</header>\\n\\n<style>\\n\\t.courier-font {\\n\\t\\tfont-family: 'Courier New', Courier, monospace;\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AA0BC,2BAAc,CACb,WAAW,CAAE,aAAa,CAAC,CAAC,OAAO,CAAC,CAAC,SACtC"}`
};
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$2);
  return `  <header class="courier-font w-full bg-white shadow-sm svelte-7rkn24" data-svelte-h="svelte-1sokboa"><div class="container mx-auto px-4 sm:px-6 lg:px-8"><div class="flex items-center justify-between py-4"><div class="flex items-center"><a href="/" class="flex items-center text-xl font-bold text-gray-800"><img src="/logo_mj.png" alt="Logo" class="h-8"></a> <nav class="ml-6"><a href="/work" class="text-gray-800 hover:text-gray-600 transition-colors duration-200">my works</a></nav></div></div></div> </header>`;
});
const css$1 = {
  code: ".courier-font.svelte-7rkn24{font-family:'Courier New', Courier, monospace}",
  map: `{"version":3,"file":"footer.svelte","sources":["footer.svelte"],"sourcesContent":["<!-- /usr/local/var/www/mjjun/src/lib/components/footer.svelte -->\\n\\n<!-- /usr/local/var/www/mjjun/src/lib/components/footer.svelte -->\\n\\n<style>\\n\\t.courier-font {\\n\\t\\tfont-family: 'Courier New', Courier, monospace;\\n\\t}\\n</style>\\n\\n<footer class=\\"courier-font bg-white border-t\\">\\n\\t<div class=\\"container mx-auto px-4 sm:px-6 lg:px-8\\">\\n\\t\\t<div\\n\\t\\t\\tclass=\\"py-6 flex flex-col sm:flex-row justify-between items-center space-y-4 sm:space-y-0 sm:space-x-4\\"\\n\\t\\t>\\n\\t\\t\\t<a\\n\\t\\t\\t\\thref=\\"https://www.instagram.com/chancecatch/\\"\\n\\t\\t\\t\\ttarget=\\"_blank\\"\\n\\t\\t\\t\\trel=\\"noopener noreferrer\\"\\n\\t\\t\\t\\tclass=\\"text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200\\"\\n\\t\\t\\t>\\n\\t\\t\\t\\tinstagram\\n\\t\\t\\t</a>\\n\\t\\t\\t<a\\n\\t\\t\\t\\thref=\\"https://www.youtube.com/@chancecatch\\"\\n\\t\\t\\t\\ttarget=\\"_blank\\"\\n\\t\\t\\t\\trel=\\"noopener noreferrer\\"\\n\\t\\t\\t\\tclass=\\"text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200\\"\\n\\t\\t\\t>\\n\\t\\t\\t\\tyoutube\\n\\t\\t\\t</a>\\n\\t\\t\\t<a\\n\\t\\t\\t\\thref=\\"https://brunch.co.kr/@c50aecc70e5f490\\"\\n\\t\\t\\t\\ttarget=\\"_blank\\"\\n\\t\\t\\t\\trel=\\"noopener noreferrer\\"\\n\\t\\t\\t\\tclass=\\"text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200\\"\\n\\t\\t\\t>\\n\\t\\t\\t\\tbrunch\\n\\t\\t\\t</a>\\n\\t\\t\\t<a\\n\\t\\t\\t\\thref=\\"https://www.linkedin.com/in/mlmj\\"\\n\\t\\t\\t\\ttarget=\\"_blank\\"\\n\\t\\t\\t\\trel=\\"noopener noreferrer\\"\\n\\t\\t\\t\\tclass=\\"text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200\\"\\n\\t\\t\\t>\\n\\t\\t\\t\\tlinkedin\\n\\t\\t\\t</a>\\n\\t\\t\\t<a\\n\\t\\t\\t\\thref=\\"mailto:myungjun1026@gmail.com\\"\\n\\t\\t\\t\\tclass=\\"text-sm text-gray-800 hover:text-gray-600 transition-colors duration-200\\"\\n\\t\\t\\t>\\n\\t\\t\\t\\temail\\n\\t\\t\\t</a>\\n\\t\\t\\t<a\\n\\t\\t\\t\\thref=\\"/resume_mj.pdf\\"\\n\\t\\t\\t\\tclass=\\"text-sm text-gray-800 hover:text-gray-600 transition-colors duration-200\\"\\n\\t\\t\\t>\\n\\t\\t\\t\\tresume\\n\\t\\t\\t</a>\\n\\t\\t\\t<p class=\\"text-sm text-gray-600\\">\\n\\t\\t\\t\\tmyungjunlee, copyright@{new Date().getFullYear()}\\n\\t\\t\\t</p>\\n\\t\\t</div>\\n\\t</div>\\n</footer>"],"names":[],"mappings":"AAKC,2BAAc,CACb,WAAW,CAAE,aAAa,CAAC,CAAC,OAAO,CAAC,CAAC,SACtC"}`
};
const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$1);
  return `   <footer class="courier-font bg-white border-t svelte-7rkn24"><div class="container mx-auto px-4 sm:px-6 lg:px-8"><div class="py-6 flex flex-col sm:flex-row justify-between items-center space-y-4 sm:space-y-0 sm:space-x-4"><a href="https://www.instagram.com/chancecatch/" target="_blank" rel="noopener noreferrer" class="text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200" data-svelte-h="svelte-uveufb">instagram</a> <a href="https://www.youtube.com/@chancecatch" target="_blank" rel="noopener noreferrer" class="text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200" data-svelte-h="svelte-1eziov2">youtube</a> <a href="https://brunch.co.kr/@c50aecc70e5f490" target="_blank" rel="noopener noreferrer" class="text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200" data-svelte-h="svelte-1vg8a6s">brunch</a> <a href="https://www.linkedin.com/in/mlmj" target="_blank" rel="noopener noreferrer" class="text-sm text-gray-600 hover:text-gray-800 transition-colors duration-200" data-svelte-h="svelte-g2rwp9">linkedin</a> <a href="mailto:myungjun1026@gmail.com" class="text-sm text-gray-800 hover:text-gray-600 transition-colors duration-200" data-svelte-h="svelte-1pzl5lr">email</a> <a href="/resume_mj.pdf" class="text-sm text-gray-800 hover:text-gray-600 transition-colors duration-200" data-svelte-h="svelte-vq8v2b">resume</a> <p class="text-sm text-gray-600">myungjunlee, copyright@${escape((/* @__PURE__ */ new Date()).getFullYear())}</p></div></div></footer>`;
});
const css = {
  code: "@font-face{font-family:'Inter';src:url('/fonts/Inter-Regular.woff2') format('woff2'),\n			url('/fonts/Inter-Regular.woff') format('woff');font-weight:normal;font-style:normal;font-display:swap}@font-face{font-family:'Inter';src:url('/fonts/Inter-Medium.woff2') format('woff2'),\n			url('/fonts/Inter-Medium.woff') format('woff');font-weight:500;font-style:normal;font-display:swap}",
  map: `{"version":3,"file":"+layout.svelte","sources":["+layout.svelte"],"sourcesContent":["<script>\\n\\timport Header from '$lib/components/header.svelte';\\n\\timport Footer from '$lib/components/footer.svelte';\\n\\timport '../app.css';\\n\\timport { fade } from 'svelte/transition';\\n\\timport { page } from '$app/stores';\\n\\timport { browser } from '$app/environment';\\n\\n\\texport let data;\\n\\n\\t$: {\\n\\t\\tif (browser) {\\n\\t\\t\\t// Update document title based on current route\\n\\t\\t\\tif ($page.url.pathname === '/') {\\n\\t\\t\\t\\tdocument.title = 'Home';\\n\\t\\t\\t} else if ($page.url.pathname === '/work') {\\n\\t\\t\\t\\tdocument.title = 'My Works';\\n\\t\\t\\t} else if ($page.url.pathname.startsWith('/work/')) {\\n\\t\\t\\t\\tconst slug = $page.url.pathname.split('/').pop();\\n\\t\\t\\t\\tif (slug.startsWith('category')) {\\n\\t\\t\\t\\t\\tconst category = decodeURIComponent($page.url.pathname.split('/').pop());\\n\\t\\t\\t\\t\\tdocument.title = category;\\n\\t\\t\\t\\t} else {\\n\\t\\t\\t\\t\\tdocument.title = \`Project \${slug}\`;\\n\\t\\t\\t\\t}\\n\\t\\t\\t}\\n\\t\\t}\\n\\t}\\n<\/script>\\n\\n<div class=\\"flex flex-col min-h-screen\\">\\n\\t<Header />\\n\\t{#key data.currentRoute}\\n\\t\\t<main\\n\\t\\t\\tclass=\\"flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-8\\"\\n\\t\\t\\tin:fade={{ duration: 150, delay: 150 }}\\n\\t\\t\\tout:fade={{ duration: 150 }}\\n\\t\\t>\\n\\t\\t\\t<slot />\\n\\t\\t</main>\\n\\t{/key}\\n\\t<Footer />\\n</div>\\n\\n<style>\\n\\t@font-face {\\n\\t\\tfont-family: 'Inter';\\n\\t\\tsrc:\\n\\t\\t\\turl('/fonts/Inter-Regular.woff2') format('woff2'),\\n\\t\\t\\turl('/fonts/Inter-Regular.woff') format('woff');\\n\\t\\tfont-weight: normal;\\n\\t\\tfont-style: normal;\\n\\t\\tfont-display: swap;\\n\\t}\\n\\n\\t@font-face {\\n\\t\\tfont-family: 'Inter';\\n\\t\\tsrc:\\n\\t\\t\\turl('/fonts/Inter-Medium.woff2') format('woff2'),\\n\\t\\t\\turl('/fonts/Inter-Medium.woff') format('woff');\\n\\t\\tfont-weight: 500;\\n\\t\\tfont-style: normal;\\n\\t\\tfont-display: swap;\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AA6CC,UAAW,CACV,WAAW,CAAE,OAAO,CACpB,GAAG,CACF,iCAAiC,CAAC,OAAO,OAAO,CAAC,CAAC;AACrD,GAAG,gCAAgC,CAAC,OAAO,MAAM,CAAC,CAChD,WAAW,CAAE,MAAM,CACnB,UAAU,CAAE,MAAM,CAClB,YAAY,CAAE,IACf,CAEA,UAAW,CACV,WAAW,CAAE,OAAO,CACpB,GAAG,CACF,gCAAgC,CAAC,OAAO,OAAO,CAAC,CAAC;AACpD,GAAG,+BAA+B,CAAC,OAAO,MAAM,CAAC,CAC/C,WAAW,CAAE,GAAG,CAChB,UAAU,CAAE,MAAM,CAClB,YAAY,CAAE,IACf"}`
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let $$unsubscribe_page;
  $$unsubscribe_page = subscribe(page, (value) => value);
  let { data } = $$props;
  if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
  $$result.css.add(css);
  $$unsubscribe_page();
  return `<div class="flex flex-col min-h-screen">${validate_component(Header, "Header").$$render($$result, {}, {}, {})} <main class="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-8">${slots.default ? slots.default({}) : ``}</main> ${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})} </div>`;
});
export {
  Layout as default
};
