import { c as create_ssr_component } from "../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return ` <div class="w-full max-w-[1120px] mx-auto h-auto flex flex-col md:flex-row justify-between items-start py-8" data-svelte-h="svelte-1q6xw1c"><div class="md:w-2/5 md:mr-8"><div class="text-[#181717] text-lg font-medium font-['Inter'] leading-snug">00 / hi there! i&#39;m mj, a machine learning engineer and data analyst</div> <div class="mt-4 text-[#606060] text-lg font-normal font-['Inter'] leading-snug">i live in calgary, canada. I started learning ai because i want to create useful services for
			people. i&#39;ve worked on many projects, but i&#39;m still figuring out which area to focus on. i
			used to plan art projects, but now i&#39;m studying computer science to change my career</div> <div class="w-full max-w-[1120px] mx-auto mt-8 border-t border-[#181717]"></div> <div class="mt-4 text-[#181717] text-lg font-medium font-['Inter'] underline leading-snug">main software</div> <div class="mt-4 text-[#606060] text-sm font-normal font-['Inter'] leading-snug">python, sveltekit, sql, tensorFlow, pytorch, docker, excel</div> <div class="mt-4 text-[#181717] text-lg font-medium font-['Inter'] underline leading-snug">main skills</div> <div class="mt-4 text-[#606060] text-sm font-normal font-['Inter'] leading-snug">machine learning, data analysis, computer vision, natural language processing, front-end
			development, sound enginner, project management</div> <div class="w-full max-w-[1120px] mx-auto mt-8 border-t border-[#181717]"></div> <div class="mt-4 text-[#181717] text-lg font-medium font-['Inter'] underline leading-snug"><a href="mailto:myungjun1026@gmail.com">myungjun1026@gmail.com</a></div> <div class="mt-4 text-[#181717] text-sm font-normal font-['Inter'] leading-snug">If you&#39;d like, you can <a href="/resume_mj.pdf">view my resume here</a></div></div> <div class="md:w-3/5 mt-8 md:mt-0 flex justify-center"><img class="w-full max-w-[720px] h-auto" src="/favicon.png" alt="MainImage"></div></div>`;
});
export {
  Page as default
};
