import { c as create_ssr_component, e as escape, d as add_attribute } from "../../chunks/ssr.js";
const css = {
  code: ".courier-font.svelte-7rkn24{font-family:'Courier New', Courier, monospace}",
  map: `{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<!-- usr/local/var/www/mjjun/src/routes/+page.svelte -->\\n\\n<script>\\n\\timport { onMount } from 'svelte';\\n\\n\\tlet imageLoaded = false;\\n\\tlet imgElement;\\n\\n\\tonMount(() => {\\n\\t\\tif (imgElement && imgElement.complete) {\\n\\t\\t\\timageLoaded = true;\\n\\t\\t}\\n\\t});\\n\\n\\tfunction handleImageLoad() {\\n\\t\\timageLoaded = true;\\n\\t}\\n<\/script>\\n\\n<main\\n\\tclass=\\"courier-font container mx-auto px-4 py-8 flex flex-col lg:flex-row justify-between items-start gap-12\\"\\n>\\n\\t<div class=\\"w-full lg:w-1/2 xl:w-3/5\\">\\n\\t\\t<section class=\\"mb-8\\">\\n\\t\\t\\t<h1 class=\\"text-gray-900 text-2xl sm:text-3xl font-medium leading-snug mb-4\\">\\n\\t\\t\\t\\t00 / hello, i'm mj, a machine learning engineer and data analyst\\n\\t\\t\\t</h1>\\n\\t\\t\\t<p class=\\"text-gray-600 text-lg font-normal leading-relaxed\\">\\n\\t\\t\\t\\ti live in calgary, canada. I started learning ai because i want to create useful services\\n\\t\\t\\t\\tfor people. i've worked on some projects, but i'm still figuring out which area to focus on.\\n\\t\\t\\t\\ti used to make art projects before, but now i'm studying computer science to change my\\n\\t\\t\\t\\tcareer\\n\\t\\t\\t</p>\\n\\t\\t\\t<div class=\\"mt-4\\">\\n\\t\\t\\t\\t<a href=\\"/resume_mj.pdf\\" class=\\"text-blue-600 hover:text-blue-800 underline\\" target=\\"_blank\\">\\n\\t\\t\\t\\t\\tView my resume\\n\\t\\t\\t\\t</a>\\n\\t\\t\\t</div>\\n\\t\\t</section>\\n\\t</div>\\n\\n\\t<div class=\\"w-full lg:w-1/2 xl:w-2/5 flex justify-center items-start\\">\\n\\t\\t<div class=\\"w-full max-w-[400px] aspect-square relative overflow-hidden rounded-lg shadow-lg {imageLoaded ? 'opacity-100' : 'opacity-0'} transition-opacity duration-300\\">\\n\\t\\t\\t<img\\n\\t\\t\\t\\tbind:this={imgElement}\\n\\t\\t\\t\\tclass=\\"absolute inset-0 w-full h-full object-cover\\"\\n\\t\\t\\t\\tsrc=\\"/favicon.png\\"\\n\\t\\t\\t\\talt=\\"profile image\\"\\n\\t\\t\\t\\ton:load={handleImageLoad}\\n\\t\\t\\t/>\\n\\t\\t</div>\\n\\t</div>\\n</main>\\n\\n<style>\\n\\t.courier-font {\\n\\t\\tfont-family: 'Courier New', Courier, monospace;\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AAuDC,2BAAc,CACb,WAAW,CAAE,aAAa,CAAC,CAAC,OAAO,CAAC,CAAC,SACtC"}`
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let imgElement;
  $$result.css.add(css);
  return `  <main class="courier-font container mx-auto px-4 py-8 flex flex-col lg:flex-row justify-between items-start gap-12 svelte-7rkn24"><div class="w-full lg:w-1/2 xl:w-3/5" data-svelte-h="svelte-1i7pr1f"><section class="mb-8"><h1 class="text-gray-900 text-2xl sm:text-3xl font-medium leading-snug mb-4">00 / hello, i&#39;m mj, a machine learning engineer and data analyst</h1> <p class="text-gray-600 text-lg font-normal leading-relaxed">i live in calgary, canada. I started learning ai because i want to create useful services
				for people. i&#39;ve worked on some projects, but i&#39;m still figuring out which area to focus on.
				i used to make art projects before, but now i&#39;m studying computer science to change my
				career</p> <div class="mt-4"><a href="/resume_mj.pdf" class="text-blue-600 hover:text-blue-800 underline" target="_blank">View my resume</a></div></section></div> <div class="w-full lg:w-1/2 xl:w-2/5 flex justify-center items-start"><div class="${"w-full max-w-[400px] aspect-square relative overflow-hidden rounded-lg shadow-lg " + escape("opacity-0", true) + " transition-opacity duration-300"}"><img class="absolute inset-0 w-full h-full object-cover" src="/favicon.png" alt="profile image"${add_attribute("this", imgElement, 0)}></div></div> </main>`;
});
export {
  Page as default
};
